---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-media-library
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.11.131
  share: /volume2/media-library
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
